### ISSUE TITLE
Feature Request: generate `AdmissionPolicy` resource manifest

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/kwctl#180]
`kwctl` supports generating `ClusterAdmissionPolicy` with the `kwctl manifest` command. This is a request to include `AdmissionPolicy` in the possible values of the `-t` argument of this command.

**Comment by ereslibre** [comment]
Given the very different nature of `ClusterAdmissionPolicy` and `AdmissionPolicy` there is also the possibility of removing the `-t` argument from `kwctl manifest`, and create two subcommands:

- `kwctl manifest clusteradmissionpolicy`: with arguments `--settings-path`, `--settings-json`, `--title`.
- `kwctl manifest admissionpolicy`:with arguments `--settings-path`, `--settings-json`, `--title`, `--namespace` (with the default namespace that it targets).

**Comment by flavio** [comment]
I think it would be nice to use the subcommand approach, that allows specific flags to be added (like the `--namespace` one)

**Comment by flavio** [comment]
This is now fixed, starting with 1.0.0-rc2
