### ISSUE TITLE
Don't try to connect to kubernetes when not needed

### ISSUE THREAD

**Issue by flavio** [kubewarden/kwctl#19]
Right now `kwctl` attempts to connect to the kubernetes cluster every time a sub-command is executed. This is not needed by some commands (eg: `annotate`), and can lead to confusing output.

For example:

```console
$ kwctl annotate -m ../safe-labels-policy/metadata.yml -o annotated.wasm ../safe-labels-policy/policy.wasm`
could not initialize a Kubernetes client due to error: Error loading kubeconfig: Failed to infer config.. cluster env: (Error loading kubeconfig: Unable to load in cluster config, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined), kubeconfig: (Error loading kubeconfig: Unable to load current context: ); contextual policies might misbehave since they will lack cluster information
```

In this case the `annotate` command worked properly, but the kubernetes context wasn't successfully retrieved. That kubernetes error happened because my minikube test cluster was currently down.

## Acceptance criteria

* The kubernetes connection is created only when needed. Right now only when `run` is used.

**Comment by ereslibre** [comment]
Fixed by https://github.com/kubewarden/kwctl/commit/5e3895655a208248af738e0ef4f7aa14fecc51f2 (and https://github.com/kubewarden/policy-evaluator/commit/4f3dca214b29ade8ee986f611e081b0607ee6bb5)
