### ISSUE TITLE
Feature Request: allow disable colorful output

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kwctl#195]
### Is your feature request related to a problem?

Sometimes, when we want to share the command output (e.g. documentation) the colors chars gets in the way of coping the output to somewhere else. 

### Solution you'd like

I would like to have a flag which disable the colorful output. Something like: `--no-color`

### Alternatives you've considered

It's possible to remove the color chars using sed:

```console
kwctl inspect registry://ghcr.io/kubewarden/policies/user-group-psp:v0.2.0 | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" 
```

**Comment by flavio** [comment]
I think this is a problem with your terminal. Here I can copy and paste without any issue from Gnome Terminal into something basic like a text file either via the shell or into Gedit...

I would close this issue

**Comment by viccuad** [comment]
I don't need it for copying manually either, but a `--no-color` could be useful if we pipe output of commands to files directly, to automate generating the expected outputs on CI.

**Comment by viccuad** [comment]
I would like to support either `--no-color` or setting [`NO_COLOR`](https://no-color.org/).

**Comment by flavio** [comment]
Fine with me

**Comment by adnanhashmi09** [comment]
I would like to work on this issue. Can you please assign it to me?

**Comment by viccuad** [comment]
@adnanhashmi09 welcome! Assigned this to you :)
