### ISSUE TITLE
Make kwctl inspect & kwctl annotate understand spec.backgroundAudit in metadata.yml

### ISSUE THREAD

**Issue by flavio** [kubewarden/kwctl#330]
# Acceptance criteria
 - [ ] kwctl inspect and kwctl annotate should accept a new backgroundAudit field in metadata.yml, analogous to mutating. The field is set to true by default
 - [ ] Provide unit & e2e tests.

**Comment by jvanz** [comment]
As discussing in a call.  @viccuad is already working on this issue while he works in the #331. Therefore, I'm assigning him to this issue as well.
