### ISSUE TITLE
Enforce policy has metadata before pushing it

### ISSUE THREAD

**Issue by flavio** [kubewarden/kwctl#34]
We should enforce all the policies to have metadata. We need that because we want to have policy-server load only policies that implement a certain version of `communication protocol`.

# Acceptance criteria

`kwctl push` refuses to publish a policy to a container registry if the policy has not been annotated.

**Comment by ereslibre** [comment]
I think we should take the development and integration use case into account.

Push can have a flag that allows pushing, even if the policy has no metadata. The policy-server will assume the latest communication protocol it knows about. In a cycle where, I as a developer, am on the develop, test cycle I think is worth having.

By default `kwctl push` will reject a push without metadata though, so you have to signal that you know what you are doing.

**Comment by flavio** [comment]
I'm fine with that, let's add a `--force` flag to the `push` command. This is going to be off by default, like you describe above.
