### ISSUE TITLE
implement kwctl tag command

### ISSUE THREAD

**Issue by raulcabello** [kubewarden/kwctl#353]
`kwctl tag` is needed for the airgap support. Once we load the policies with kwctl in our airgapped environment, we need to be able to change the registry of the policy before pushing it to the private registry. This should be done with `kwctl tag`, which should be similar to the [docker tag](https://docs.docker.com/engine/reference/commandline/tag/) command. Rancher script uses `docker tag` for doing this step.

Usage:

```
kwctl tag SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]
```

**Comment by flavio** [comment]
Are you sure this has been done? I think the issue might have been closed by mistake

**Comment by raulcabello** [comment]
It hasn't been done, but we don't needed for airgap in the end. Same can be achieve with `kwctl push` which admit the policy and uri destination as a parameter (unlike `docker push`). I archived it in the board, but it was still appearing in the issues that's why I closed it.
I should have added this info when I closed it. Sorry about that.
