### ISSUE TITLE
kwctl does not fail in case it can not read the docker config.json

### ISSUE THREAD

**Issue by Martin-Weiss** [kubewarden/kwctl#362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

During troubleshooting kwctl image pull from authenticated registry I had to specify the parameter `--docker-config-json-path` and had the false understanding that this does not only take the path to a `config.json` but I can also specify the json i.e. via `--docker-config-json-path /root/oci/reg-auth.json`

Unfortunately the putput of kwctl did not give any info that the file could not be read and just in the strace I could find out that it tried to read /root/oci/reg-auth.json/config.json

### Expected Behavior

In case the config.json specified can not be read / does not exist - kwctl should thrown an error  message for the user.

### Steps To Reproduce

Use kwctl and specify a non existing or non readable --docker-config-json-path

### Environment

```markdown
- OS: Linux
- Architecture: x86_64
```

**Comment by flavio** [comment]
Closing, starting with version 1.6.0 kwctl will print an error message if it cannot find a `config.json` file inside of the directory specified by the user
