### ISSUE TITLE
Airgap kubewarden-save-images.sh and kubewarden-load-images.sh are not released

### ISSUE THREAD

**Issue by kravciak** [kubewarden/kwctl#383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[Documentation](https://docs.kubewarden.io/operator-manual/airgap/install#save-container-images-in-your-workstation) for airgap says:

```
Step 3. Download kubewarden-save-images.sh and kubewarden-load-images.sh from the latest kwctl [release](https://github.com/kubewarden/kwctl/releases).
```

Those scripts are available only in version 1.4.0, but not in latest (1.4.1).

### Expected Behavior

Scripts are available for every release

**Comment by jvanz** [comment]
I've fixed the last 2 releases missing the file by uploading the files manually in the release.
