### ISSUE TITLE
kwctl v1.5.0 reports that it's v1.4.2

### ISSUE THREAD

**Issue by p-linnane** [kubewarden/kwctl#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Building kwctl v1.5.0 from source for [Homebrew](https://github.com/Homebrew/homebrew-core/actions/runs/3964892088/). After building, running `kwctl --version` reports v1.4.2.

### Expected Behavior

`kwctl --version` reports v1.5.0

### Steps To Reproduce

Build kwctl v1.5.0 using `cargo install`
Run `kwctl --version`
Version v1.4.2 is returned

### Environment

```markdown
- OS: macOS
- Architecture: arm64
```

**Comment by flavio** [comment]
@p-linnane thanks for having reported this issue. I've just tagged kwctl 1.5.1, the binaries are being built as we speak
