### ISSUE TITLE
Fix kwctl coverage and reach close to 70%

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kwctl#852]
### Acceptance criteria

In reality, we have ~65% code coverage already.  Check why codecov coverage is not recognizing the tests.
Add the needed tests to reach ~70% coverage.

**Comment by flavio** [comment]
We need to fix the codecov configuration, I just checked and we have only [13% of code coverage](https://app.codecov.io/gh/kubewarden/kwctl) which is wrong
