### ISSUE TITLE
Spike: decide how to run PolicyGroups using kwctl

### ISSUE THREAD

**Issue by flavio** [kubewarden/kwctl#906]
Starting from Kubewarden 1.17 a new type of policy is introduced: PolicyGroup. The purpose and details of this policy type are covered by [this dedicated RFC](https://github.com/kubewarden/rfc/blob/main/rfc/0021-policy-group.md).

The purpose of this issue is to define how `kwctl run` should be used to run PolicyGroup.

**Comment by flavio** [comment]
I like this approach because it also provides a generic way to run any kind of Kubewarden CRD outside of the cluster, just for testing purposes.

**Comment by viccuad** [comment]
Agree also.

**Comment by jvanz** [comment]
Yeap, nice approach! :+1:

**Comment by flavio** [comment]
Closing, I've created a dedicated issue for implementing what we've agreed. See https://github.com/kubewarden/kwctl/issues/967
