### ISSUE TITLE
[Feature request] Set a name with `kwctl manifest`

### ISSUE THREAD

**Issue by nunix** [kubewarden/kwctl#96]
[Actual state]
Currently, when generating a `ClusterAdmissionPolicy` with `kwctl manifest`, the `metadata[].name` value is set to "generated-policy".

Therefore, if we apply the manifest as is, with `kubectl`, then we get the following output:
```shell
kubectl get clusteradmissionpolicies.policies.kubewarden.io
NAME               POLICY SERVER   MUTATING   STATUS
generated-policy   default         false      active
```

[Desired state]
It would be nice to have a "command switch" to set the name and if no value is provided, then the title of the policy is set (note: I used title to be aligned with `kwctl inspect` output)

Hope it makes sense 😄

**Comment by ereslibre** [comment]
Thank you @nunix! I think it makes a lot of sense, and a nice UX improvement for kwctl.
